In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [6]:
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8",
    "Accept-Language": "en-US,en;q=0.9"
}
wbpg=requests.get("https://www.ambitionbox.com/list-of-companies?page=1", headers=headers ).text

In [7]:
soup=BeautifulSoup(wbpg,'lxml')

In [ ]:
print(soup.prettify())

In [41]:
comp=soup.find_all('div' ,class_="companyCardWrapper")

In [42]:
comp

[<div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="1" itemprop="position"/> <meta content="TCS" itemprop="name"/> <meta content="Tata Consultancy Services" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/tcs-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/tcs.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Tata Consultancy Services logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vdGNzLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="TCS">
 									TCS
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#FFBA01" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.3<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(1.2L)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +445 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsup logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsUp.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--high">Highly Rated For</span></div> <span class="companyCardWrapper__ratingValues">Job Security</span></div> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/tcs-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">1.2L</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/tcs-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">10.2L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/tcs-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">11.5k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/tcs-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">4.6k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/tcs-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">10.8k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/tcs-photos" target="_blank"><span class="companyCardWrapper__ActionCount">93</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="2" itemprop="position"/> <meta content="Accenture" itemprop="name"/> <meta content="Accenture overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/accenture-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/accenture.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Accenture logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vYWNjZW50dXJlLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName companyCardWrapper__companyName--m8"><h2 class="companyCardWrapper__companyName" title="Accenture">
 									Accenture
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#9acd32" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.7<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(74.2k)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +259 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><!-- --> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/accenture-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">74.2k</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/accenture-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">7.1L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/accenture-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">9.4k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/accenture-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">36.9k</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/accenture-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">6.8k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/accenture-photos" target="_blank"><span class="companyCardWrapper__ActionCount">49</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="3" itemprop="position"/> <meta content="Wipro" itemprop="name"/> <meta content="Wipro overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/wipro-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/wipro.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Wipro logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vd2lwcm8tb3JpZ2luYWwuanBn.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="Wipro">
 									Wipro
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#9acd32" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.6<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(65.6k)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Hyderabad +374 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><!-- --> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/wipro-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">65.6k</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/wipro-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">4.9L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/wipro-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">6.9k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/wipro-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">325</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/wipro-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">4.8k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/wipro-photos" target="_blank"><span class="companyCardWrapper__ActionCount">114</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="4" itemprop="position"/> <meta content="Cognizant" itemprop="name"/> <meta content="Cognizant overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/cognizant-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/cognizant-d.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Cognizant logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vY29nbml6YW50LW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="Cognizant">
 									Cognizant
 								</h2></a> <!-- --></div> <button arialabel="Follow" class="companyCardWrapper__FollowCTA g-btn g-btn--text g-btn--md" data-testid="" title="Follow" type="button"><!-- --> <span class="g-btn__label g-btn__label--md g-btn__label--text g-btn__label--loader">Follow</span> <!-- --> <!-- --></button> <!-- --></div> <div class="companyCardWrapper__ratingWrapper"><div class="companyCardWrapper__companyRatingWrapper"><div class="companyCardWrapper__companyRating"><div class="rating_star_container" style="line-height:20px;"><svg fill="none" height="20" viewbox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg"><rect fill="#9acd32" height="20" rx="4" width="20"></rect> <path d="M6.295 16L7.27 11.5632L4 8.57895L8.32 8.18421L10 4L11.68 8.18421L16 8.57895L12.73 11.5632L13.705 16L10 13.6474L6.295 16Z" fill="white"></path></svg> <div class="rating_text rating_text--md"><div style="height:auto;">
 			3.7<!-- --></div></div></div></div> <span class="companyCardWrapper__companyRatingCount">
 								(62k)
 							</span></div> <span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Hyderabad +233 other locations
 						</span> <!-- --> <div class="companyCardWrapper__ratingComparisonWrapper"><!-- --> <div><div class="companyCardWrapper__ratingHeader"><img alt="thumbsdown logo" height="14px" src="https://static.ambitionbox.com/static/companyListing/ThumbsDown.svg" width="14px"/> <span class="companyCardWrapper__ratingHeader--critical">Critically Rated For</span></div> <span class="companyCardWrapper__ratingValues">Promotions, Salary, Work Satisfaction</span></div></div></div> <div class="viewSalaryInsights"><div class="salaryInsightsText">To view salary insights</div> <div class="designationSelectionText">
 							Select designation
 						</div></div> <!-- --></div></div> <div class="companyCardWrapper__tertiaryInformation"><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/reviews/cognizant-reviews" target="_blank"><span class="companyCardWrapper__ActionCount">62k</span> <span class="companyCardWrapper__ActionTitle">Reviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/salaries/cognizant-salaries" target="_blank"><span class="companyCardWrapper__ActionCount">6.1L</span> <span class="companyCardWrapper__ActionTitle">Salaries</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/interviews/cognizant-interview-questions" target="_blank"><span class="companyCardWrapper__ActionCount">6.5k</span> <span class="companyCardWrapper__ActionTitle">Interviews</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/jobs/cognizant-jobs-cmp" target="_blank"><span class="companyCardWrapper__ActionCount">697</span> <span class="companyCardWrapper__ActionTitle">Jobs</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/benefits/cognizant-benefits" target="_blank"><span class="companyCardWrapper__ActionCount">5.6k</span> <span class="companyCardWrapper__ActionTitle">Benefits</span></a><a class="companyCardWrapper__ActionWrapper" href="https://www.ambitionbox.com/photos/cognizant-photos" target="_blank"><span class="companyCardWrapper__ActionCount">102</span> <span class="companyCardWrapper__ActionTitle">Photos</span></a></div></div>,
 <div class="companyCardWrapper" itemprop="itemListElement" itemscope="itemscope" itemtype="http://schema.org/ListItem"><meta content="5" itemprop="position"/> <meta content="Capgemini" itemprop="name"/> <meta content="Capgemini overview" itemprop="alternateName"/> <meta content="https://www.ambitionbox.com/overview/capgemini-overview" itemprop="url"/> <meta content="https://static.ambitionbox.com/alpha/company/photos/logos/capgemini-d.jpg" itemprop="image"/> <div class="companyCardWrapper__primaryInformation"><div class="companyCardWrapper__companyLogo"><img alt="Capgemini logo" height="50" loading="lazy" onerror="this.onerror=null;this.src='/static/icons/company-placeholder.svg';" src="https://static.ambitionbox.com/assets/v2/images/rs:fit:200:200:false:false/aHR0cHM6Ly9tZWRpYS5uYXVrcmkuY29tL21lZGlhL2FiY29tcGxvZ28vY2FwZ2VtaW5pLW9yaWdpbmFsLmpwZw.webp" width="50"/></div> <div class="companyCardWrapper__metaInformation"><div class="companyCardWrapper__header"><div class="companyCardWrapper__companyPrimaryDetailsTopSection"><a class="companyCardWrapper__companyName"><h2 class="companyCardWrapper__companyName" title="Capgemini">
 									Capgemini

In [72]:
name=[]
rating=[]
review_count=[]
sal=[]

for i in comp:
  name.append(i.find('h2').text.strip())
  rating.append(i.find('div',class_='rating_star_container').text.strip())
  review_count.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[0].text.strip())
  sal.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[1].text.strip())

In [50]:
name

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'HCLTech',
 'ICICI Bank',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Jio',
 'Axis Bank',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTIMindtree',
 'IBM']

In [54]:
rating

['3.3',
 '3.7',
 '3.6',
 '3.7',
 '3.6',
 '3.8',
 '3.5',
 '3.4',
 '3.9',
 '3.4',
 '3.6',
 '3.9',
 '4.4',
 '3.6',
 '3.6',
 '3.9',
 '3.9',
 '4.6',
 '3.6',
 '3.9']

In [65]:
review_count

['1.2L',
 '74.2k',
 '65.6k',
 '62k',
 '54k',
 '53k',
 '49.3k',
 '46.4k',
 '46.3k',
 '43.7k',
 '42.8k',
 '39k',
 '33.8k',
 '33.6k',
 '32.5k',
 '31.7k',
 '27.5k',
 '27.3k',
 '26.7k',
 '25.9k']

In [73]:
sal

['10.2L',
 '7.1L',
 '4.9L',
 '6.1L',
 '4.9L',
 '1.5L',
 '5.3L',
 '3.9L',
 '1.5L',
 '2.9L',
 '2.4L',
 '100k',
 '62.1k',
 '1L',
 '1.3L',
 '1.6L',
 '74.4k',
 '24.9k',
 '2L',
 '2.2L']

In [74]:
df={'name':name,'review':review_count,'rating':rating,'salary':sal}

In [75]:
df

{'name': ['TCS',
  'Accenture',
  'Wipro',
  'Cognizant',
  'Capgemini',
  'HDFC Bank',
  'Infosys',
  'HCLTech',
  'ICICI Bank',
  'Tech Mahindra',
  'Genpact',
  'TP',
  'Jio',
  'Axis Bank',
  'Concentrix Corporation',
  'Amazon',
  'Reliance Retail',
  'iEnergizer',
  'LTIMindtree',
  'IBM'],
 'review': ['1.2L',
  '74.2k',
  '65.6k',
  '62k',
  '54k',
  '53k',
  '49.3k',
  '46.4k',
  '46.3k',
  '43.7k',
  '42.8k',
  '39k',
  '33.8k',
  '33.6k',
  '32.5k',
  '31.7k',
  '27.5k',
  '27.3k',
  '26.7k',
  '25.9k'],
 'rating': ['3.3',
  '3.7',
  '3.6',
  '3.7',
  '3.6',
  '3.8',
  '3.5',
  '3.4',
  '3.9',
  '3.4',
  '3.6',
  '3.9',
  '4.4',
  '3.6',
  '3.6',
  '3.9',
  '3.9',
  '4.6',
  '3.6',
  '3.9'],
 'salary': ['10.2L',
  '7.1L',
  '4.9L',
  '6.1L',
  '4.9L',
  '1.5L',
  '5.3L',
  '3.9L',
  '1.5L',
  '2.9L',
  '2.4L',
  '100k',
  '62.1k',
  '1L',
  '1.3L',
  '1.6L',
  '74.4k',
  '24.9k',
  '2L',
  '2.2L']}

In [77]:
data=pd.DataFrame(df)

In [78]:
data

                      name review rating salary
0                      TCS   1.2L    3.3  10.2L
1                Accenture  74.2k    3.7   7.1L
2                    Wipro  65.6k    3.6   4.9L
3                Cognizant    62k    3.7   6.1L
4                Capgemini    54k    3.6   4.9L
5                HDFC Bank    53k    3.8   1.5L
6                  Infosys  49.3k    3.5   5.3L
7                  HCLTech  46.4k    3.4   3.9L
8               ICICI Bank  46.3k    3.9   1.5L
9            Tech Mahindra  43.7k    3.4   2.9L
10                 Genpact  42.8k    3.6   2.4L
11                      TP    39k    3.9   100k
12                     Jio  33.8k    4.4  62.1k
13               Axis Bank  33.6k    3.6     1L
14  Concentrix Corporation  32.5k    3.6   1.3L
15                  Amazon  31.7k    3.9   1.6L
16         Reliance Retail  27.5k    3.9  74.4k
17              iEnergizer  27.3k    4.6  24.9k
18             LTIMindtree  26.7k    3.6     2L
19                     IBM  25.9k    3.9   2.2L

In [10]:
final=pd.DataFrame()
for j in range(1,15):
    url="https://www.ambitionbox.com/list-of-companies?page={}".format(j)

    headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8",
    "Accept-Language": "en-US,en;q=0.9"
}
    wbpg=requests.get(url, headers=headers ).text
    soup=BeautifulSoup(wbpg,'lxml')
    comp=soup.find_all('div' ,class_="companyCardWrapper")
    name=[]
    rating=[]
    review_count=[]
    sal=[]

    for i in comp:
     name.append(i.find('h2').text.strip())
     rating.append(i.find('div',class_='rating_star_container').text.strip())
     review_count.append(i.find_all('span',class_='companyCardWrapper__ActionCount')[0].text.strip())
     sal.append(i.find_all('span',class_="companyCardWrapper__ActionCount")[1].text.strip())
    df={'name':name,'review':review_count,'rating':rating,'salary':sal}
    data=pd.DataFrame(df)
    final = pd.concat([final, data], ignore_index=True)

In [11]:
final

                                        name review rating salary
0                                        TCS   1.2L    3.3  10.2L
1                                  Accenture  74.2k    3.7   7.1L
2                                      Wipro  65.6k    3.6   4.9L
3                                  Cognizant    62k    3.7   6.1L
4                                  Capgemini    54k    3.6   4.9L
..                                       ...    ...    ...    ...
275           Amazon Transportation Services   3.2k    4.2   8.8k
276                           Dilip Buildcon   3.2k    3.9   8.1k
277  Societe Generale Global Solution Centre   3.2k    3.6  23.6k
278                               S&P Global   3.2k    4.0    21k
279                                  Walmart   3.2k    3.5  24.5k

[280 rows x 4 columns]